# resolve-type-names: false

class ::SavedQuery < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::SavedQuery, ::SavedQuery::ActiveRecord_Relation, ::Integer]

  module ::SavedQuery::GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::Integer

    def id_for_database: () -> ::Integer

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def name: () -> ::String

    def name=: (::String) -> ::String

    def name?: () -> bool

    def name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_change: () -> [ ::String?, ::String? ]

    def name_will_change!: () -> void

    def name_was: () -> ::String?

    def name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def name_previous_change: () -> ::Array[::String?]?

    def name_previously_was: () -> ::String?

    def name_before_last_save: () -> ::String?

    def name_change_to_be_saved: () -> ::Array[::String?]?

    def name_in_database: () -> ::String?

    def saved_change_to_name: () -> ::Array[::String?]?

    def saved_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def name_before_type_cast: () -> ::String

    def name_for_database: () -> ::String

    def query_params: () -> untyped

    def query_params=: (untyped) -> untyped

    def query_params?: () -> bool

    def query_params_changed?: (?from: untyped, ?to: untyped) -> bool

    def query_params_change: () -> [ untyped, untyped ]

    def query_params_will_change!: () -> void

    def query_params_was: () -> untyped

    def query_params_previously_changed?: (?from: untyped, ?to: untyped) -> bool

    def query_params_previous_change: () -> ::Array[untyped]?

    def query_params_previously_was: () -> untyped

    def query_params_before_last_save: () -> untyped

    def query_params_change_to_be_saved: () -> ::Array[untyped]?

    def query_params_in_database: () -> untyped

    def saved_change_to_query_params: () -> ::Array[untyped]?

    def saved_change_to_query_params?: (?from: untyped, ?to: untyped) -> bool

    def will_save_change_to_query_params?: (?from: untyped, ?to: untyped) -> bool

    def restore_query_params!: () -> void

    def clear_query_params_change: () -> void

    def query_params_before_type_cast: () -> untyped

    def query_params_for_database: () -> untyped

    def resource_type: () -> ::String

    def resource_type=: (::String) -> ::String

    def resource_type?: () -> bool

    def resource_type_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def resource_type_change: () -> [ ::String?, ::String? ]

    def resource_type_will_change!: () -> void

    def resource_type_was: () -> ::String?

    def resource_type_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def resource_type_previous_change: () -> ::Array[::String?]?

    def resource_type_previously_was: () -> ::String?

    def resource_type_before_last_save: () -> ::String?

    def resource_type_change_to_be_saved: () -> ::Array[::String?]?

    def resource_type_in_database: () -> ::String?

    def saved_change_to_resource_type: () -> ::Array[::String?]?

    def saved_change_to_resource_type?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_resource_type?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_resource_type!: () -> void

    def clear_resource_type_change: () -> void

    def resource_type_before_type_cast: () -> ::String

    def resource_type_for_database: () -> ::String

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time

    def user_id: () -> ::Integer

    def user_id=: (::Integer) -> ::Integer

    def user_id?: () -> bool

    def user_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def user_id_change: () -> [ ::Integer?, ::Integer? ]

    def user_id_will_change!: () -> void

    def user_id_was: () -> ::Integer?

    def user_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def user_id_previous_change: () -> ::Array[::Integer?]?

    def user_id_previously_was: () -> ::Integer?

    def user_id_before_last_save: () -> ::Integer?

    def user_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def user_id_in_database: () -> ::Integer?

    def saved_change_to_user_id: () -> ::Array[::Integer?]?

    def saved_change_to_user_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_user_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_user_id!: () -> void

    def clear_user_id_change: () -> void

    def user_id_before_type_cast: () -> ::Integer

    def user_id_for_database: () -> ::Integer
  end
  include ::SavedQuery::GeneratedAttributeMethods
  module ::SavedQuery::GeneratedAliasAttributeMethods
    include ::SavedQuery::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::SavedQuery::GeneratedAliasAttributeMethods

  def user: () -> ::User
  def user=: (::User?) -> ::User?
  def reload_user: () -> ::User?
  def build_user: (?untyped) -> ::User
  def create_user: (?untyped) -> ::User
  def create_user!: (?untyped) -> ::User

  module ::SavedQuery::GeneratedAssociationMethods
  end
  include ::SavedQuery::GeneratedAssociationMethods

  def self.for_resource: (untyped type) -> ::SavedQuery::ActiveRecord_Relation

  module ::SavedQuery::GeneratedRelationMethods
    def for_resource: (untyped type) -> ::SavedQuery::ActiveRecord_Relation
  end

  class ::SavedQuery::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::SavedQuery]
    include ::SavedQuery::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::SavedQuery, ::Integer]
  end

  class ::SavedQuery::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::SavedQuery]
    include ::SavedQuery::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::SavedQuery, ::Integer]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SavedQuery
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SavedQuery]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SavedQuery
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SavedQuery]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::SavedQuery
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::SavedQuery]
    def reload: () -> ::Array[::SavedQuery]

    def replace: (::Array[::SavedQuery]) -> void
    def delete: (*::SavedQuery | ::Integer) -> ::Array[::SavedQuery]
    def destroy: (*::SavedQuery | ::Integer) -> ::Array[::SavedQuery]
    def <<: (*::SavedQuery | ::Array[::SavedQuery]) -> self
    def prepend: (*::SavedQuery | ::Array[::SavedQuery]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::User < ::ApplicationRecord
end
