# frozen_string_literal: true

require "prawn"
require "prawn/table"

# Generates a PDF document for a completed report.
#
# Usage:
#   pdf_data = ReportPdfExporter.generate(report)
#
class ReportPdfExporter
  class << self
    def generate(report)
      template = report.template
      result   = report.result_data.deep_symbolize_keys

      Prawn::Document.new(page_size: "LETTER", page_layout: :landscape) do |pdf|
        # Title
        pdf.text report.title, size: 18, style: :bold
        pdf.move_down 4

        # Metadata
        pdf.text "Report type: #{template.title}", size: 10, color: "666666"
        pdf.text "Generated: #{report.completed_at&.strftime('%b %d, %Y at %l:%M %p')}", size: 10, color: "666666"
        pdf.text "Generated by: #{report.generated_by.name || report.generated_by.email_address}", size: 10, color: "666666"
        pdf.move_down 8

        # Summary
        if result[:summary].present?
          render_summary(pdf, result[:summary])
          pdf.move_down 12
        end

        # Chart
        if result[:chart].present?
          render_chart(pdf, result[:chart], template.chart_type)
          pdf.move_down 12
        end

        # Data table
        if result[:table].present? && template.table_columns.present?
          render_table(pdf, template, result[:table])
        end

        # Footer with page numbers
        pdf.number_pages "Page <page> of <total>",
          at: [ pdf.bounds.left, -4 ],
          size: 8,
          color: "999999"
      end.render
    end

    private

      def render_summary(pdf, summary)
        pdf.text "Summary", size: 13, style: :bold
        pdf.move_down 4

        summary.each do |key, value|
          label = key.to_s.titleize
          pdf.text "#{label}: #{value}", size: 10
        end
      end

      def render_chart(pdf, chart_data, chart_type)
        png_blob = ReportChartRenderer.render(chart_data, chart_type: chart_type)

        pdf.text "Chart", size: 13, style: :bold
        pdf.move_down 4

        # Embed the PNG into the PDF, scaled to fit the page width
        pdf.image StringIO.new(png_blob), width: pdf.bounds.width, position: :center
      rescue StandardError => e
        Rails.logger.error { "[ReportPdfExporter] Chart rendering failed: #{e.message}" }
        pdf.text "(Chart could not be rendered)", size: 10, color: "999999", style: :italic
      end

      def render_table(pdf, template, table_data)
        columns = template.table_columns
        header  = columns.map { |col| col[:label] }
        rows    = table_data.map do |row|
          row = row.symbolize_keys
          columns.map { |col| row[col[:key].to_sym].to_s }
        end

        pdf.text "Details", size: 13, style: :bold
        pdf.move_down 4

        pdf.table([ header ] + rows,
          header: true,
          width: pdf.bounds.width,
          cell_style: { size: 9, padding: [ 4, 6, 4, 6 ] },
          row_colors: [ "F8F8F8", "FFFFFF" ]
        ) do
          row(0).font_style = :bold
          row(0).background_color = "4472C4"
          row(0).text_color = "FFFFFF"
        end
      end
  end
end
