# frozen_string_literal: true

require "caxlsx"

# Generates an Excel (.xlsx) workbook for a completed report.
#
# The workbook contains:
#   - A "Summary" sheet with report metadata and summary stats
#   - A "Data" sheet with the full result table
#
# Usage:
#   xlsx_data = ReportExcelExporter.generate(report)
#
class ReportExcelExporter
  class << self
    def generate(report)
      template = report.template
      result   = report.result_data.deep_symbolize_keys

      package = Axlsx::Package.new
      workbook = package.workbook

      header_style = workbook.styles.add_style(
        b: true, bg_color: "4472C4", fg_color: "FFFFFF", sz: 11,
        border: { style: :thin, color: "000000" }
      )
      body_style = workbook.styles.add_style(sz: 10)
      bold_style = workbook.styles.add_style(b: true, sz: 11)

      # Summary sheet
      add_summary_sheet(workbook, report, template, result, bold_style: bold_style, body_style: body_style)

      # Data sheet
      if result[:table].present? && template.table_columns.present?
        add_data_sheet(workbook, template, result[:table], header_style: header_style, body_style: body_style)
      end

      package.to_stream.read
    end

    private

      def add_summary_sheet(workbook, report, template, result, bold_style:, body_style:)
        workbook.add_worksheet(name: "Summary") do |sheet|
          sheet.add_row [ "Report" ], style: bold_style
          sheet.add_row [ "Title", report.title ], style: body_style
          sheet.add_row [ "Type", template.title ], style: body_style
          sheet.add_row [ "Generated", report.completed_at&.strftime("%b %d, %Y at %l:%M %p") ], style: body_style
          sheet.add_row [ "Generated by", report.generated_by.name || report.generated_by.email_address ], style: body_style
          sheet.add_row []

          if result[:summary].present?
            sheet.add_row [ "Summary" ], style: bold_style
            result[:summary].each do |key, value|
              sheet.add_row [ key.to_s.titleize, value.to_s ], style: body_style
            end
          end

          sheet.column_widths 25, 40
        end
      end

      def add_data_sheet(workbook, template, table_data, header_style:, body_style:)
        columns = template.table_columns

        workbook.add_worksheet(name: "Data") do |sheet|
          # Header row
          sheet.add_row columns.map { |col| col[:label] }, style: header_style

          # Data rows
          table_data.each do |row|
            row = row.symbolize_keys
            values = columns.map { |col| row[col[:key].to_sym].to_s }
            sheet.add_row values, style: body_style
          end

          # Auto-width columns
          sheet.column_widths(*columns.map { |col| [ col[:label].length + 6, 30 ].min })
        end
      end
  end
end
