-- SQL Dump of EI_PLACE_2022.mdb
-- generated by MDB Viewer 6
-- optimized for PostgreSQL

SET NAMES 'UTF8';

DROP TABLE IF EXISTS "Act_Outstand";

CREATE TABLE "Act_Outstand" (
    "Date_Created" TIMESTAMP,
    "Time_Created" TIMESTAMP,
    "Tran_Ref" DOUBLE PRECISION,
    "Ref" TEXT,
    "Title" TEXT,
    "Return_Status" TEXT,
    "Member_Number" TEXT,
    "Cost" DOUBLE PRECISION,
    "Tax" DOUBLE PRECISION,
    "Tax2" DOUBLE PRECISION,
    "Added_By" TEXT,
    "Note_X" TEXT,
    "Returned_By" TEXT,
    "Ident_Var" TEXT
);


DROP TABLE IF EXISTS "CD_Sessions";

CREATE TABLE "CD_Sessions" (
    "Date_Log" TIMESTAMP,
    "Time_Log" TIMESTAMP,
    "Session_cnt" INTEGER,
    "Session_id" DOUBLE PRECISION,
    "Amt_Value" DOUBLE PRECISION,
    "User_Name" TEXT,
    "Entry_Code" TEXT
);


DROP TABLE IF EXISTS "Company";

CREATE TABLE "Company" (
    "Key" TEXT,
    "Comp_Name" TEXT,
    "Address1" TEXT,
    "Address2" TEXT,
    "Address3" TEXT,
    "Address4" TEXT,
    "Address5" TEXT,
    "Tel" TEXT,
    "Email" TEXT,
    "Logo" TEXT
);


DROP TABLE IF EXISTS "Current_Loans";

CREATE TABLE "Current_Loans" (
    "Date_Created" TIMESTAMP,
    "Time_Created" TIMESTAMP,
    "Tran_Ref" DOUBLE PRECISION,
    "Ref" TEXT,
    "Title" TEXT,
    "Status" TEXT,
    "Member_Number" TEXT,
    "Due_Date" TIMESTAMP,
    "Cost" DOUBLE PRECISION,
    "Tax" DOUBLE PRECISION,
    "Tax2" DOUBLE PRECISION,
    "Added_By" TEXT,
    "Fr_Rent_Pts" TEXT,
    "Note_X" TEXT,
    "Session_id" DOUBLE PRECISION,
    "Rented_By" TEXT,
    "R_Plan" TEXT,
    "Promo_Code" TEXT
);


DROP TABLE IF EXISTS "Customers";

CREATE TABLE "Customers" (
    "Customer_Name" TEXT,
    "Member_Number" TEXT,
    "Customer_Address1" TEXT,
    "Customer_Phone" TEXT,
    "Customer_Email" TEXT,
    "Account_Status" DOUBLE PRECISION,
    "Password" TEXT,
    "PIN" TEXT,
    "Remarks" TEXT,
    "Joining_Date" TIMESTAMP,
    "Date_Created" TIMESTAMP,
    "Passport_Photo" TEXT,
    "ID_Provided" TEXT,
    "DOB" TEXT,
    "C_Card" TEXT,
    "CC_exp" TEXT,
    "Spare1" TIMESTAMP,
    "Spare2" TEXT,
    "Added_By" TEXT,
    "Active" TEXT,
    "Fr_Rent_Pts" TEXT,
    "Custom1" TEXT,
    "Custom2" TEXT,
    "Custom3" TEXT,
    "Custom4" TEXT,
    "Rating_Perm" TEXT,
    "FamName1" TEXT,
    "FamName2" TEXT,
    "FamName3" TEXT,
    "FamName4" TEXT,
    "FamRat1" TEXT,
    "FamRat2" TEXT,
    "FamRat3" TEXT,
    "FamRat4" TEXT,
    "FamDOB1" TIMESTAMP,
    "FamDOB2" TIMESTAMP,
    "FamDOB3" TIMESTAMP,
    "FamDOB4" TIMESTAMP,
    "FamPhoto1" TEXT,
    "FamPhoto2" TEXT,
    "FamPhoto3" TEXT,
    "FamPhoto4" TEXT,
    "Discount" TEXT,
    "Discount2" TEXT,
    "Mem_Fee_Date" TEXT,
    "Mem_Fee" TEXT,
    "Prepaid" DOUBLE PRECISION,
    "MaxRentals" INTEGER,
    "Plan_Name" TEXT,
    "Plan_Expiry" TIMESTAMP,
    "Plan_Started" TIMESTAMP,
    "Deposit_Pd" DOUBLE PRECISION,
    "Alert" TEXT,
    "Tax_Ex" TEXT
);


DROP TABLE IF EXISTS "Holiday_Dates";

CREATE TABLE "Holiday_Dates" (
    "Hol_Date" TIMESTAMP
);


DROP TABLE IF EXISTS "Paste Errors";

CREATE TABLE "Paste Errors" (
    "F1" TEXT,
    "F2" TEXT,
    "F3" TEXT,
    "F4" DOUBLE PRECISION,
    "F5" DOUBLE PRECISION,
    "F6" TEXT,
    "F7" TEXT,
    "F8" TEXT,
    "F9" TEXT,
    "F10" TEXT,
    "F11" TEXT,
    "F12" TEXT,
    "F13" TEXT,
    "F14" TEXT,
    "F15" TEXT,
    "F16" TEXT,
    "F17" TEXT,
    "F18" TEXT,
    "F19" TEXT,
    "F20" TEXT
);


DROP TABLE IF EXISTS "Payments_Made";

CREATE TABLE "Payments_Made" (
    "DateT_Created" TIMESTAMP,
    "Tran_Ref" DOUBLE PRECISION,
    "Total_Due" DOUBLE PRECISION,
    "Cash_Pd" DOUBLE PRECISION,
    "CC_Paid" DOUBLE PRECISION,
    "CQ_Paid" DOUBLE PRECISION,
    "OT_Paid" DOUBLE PRECISION,
    "Session_ID" DOUBLE PRECISION
);


DROP TABLE IF EXISTS "Promocombo";

CREATE TABLE "Promocombo" (
    "Number" INTEGER,
    "Quantity" DOUBLE PRECISION,
    "Category" TEXT,
    "Product_Ref" TEXT
);


DROP TABLE IF EXISTS "PromoCross";

CREATE TABLE "PromoCross" (
    "Number" INTEGER,
    "Quantity" DOUBLE PRECISION,
    "Category" TEXT,
    "Category2" TEXT,
    "Day2" TEXT,
    "Day3" TEXT,
    "Day4" TEXT,
    "Day5" TEXT,
    "Day6" TEXT,
    "Day7" TEXT,
    "Day1" TEXT
);


DROP TABLE IF EXISTS "PromoEReturn";

CREATE TABLE "PromoEReturn" (
    "Number" INTEGER,
    "Time_1" DOUBLE PRECISION,
    "Time_2" DOUBLE PRECISION,
    "Credit_Given" DOUBLE PRECISION,
    "Rental_Category" TEXT
);


DROP TABLE IF EXISTS "Promotions";

CREATE TABLE "Promotions" (
    "Number" INTEGER,
    "Quantity" DOUBLE PRECISION,
    "Category" TEXT,
    "Total_Price" DOUBLE PRECISION,
    "Days" INTEGER,
    "Day2" TEXT,
    "Day3" TEXT,
    "Day4" TEXT,
    "Day5" TEXT,
    "Day6" TEXT,
    "Day7" TEXT,
    "Day1" TEXT
);


DROP TABLE IF EXISTS "Rental_Categories";

CREATE TABLE "Rental_Categories" (
    "Number" INTEGER,
    "Rental_Category" TEXT,
    "Rental_Time" INTEGER,
    "Rental_Cost" DOUBLE PRECISION,
    "Fine" DOUBLE PRECISION,
    "Fr_Rent_Pts" TEXT,
    "Pts_To_Rent" TEXT,
    "1_Day" DOUBLE PRECISION,
    "2_Day" DOUBLE PRECISION,
    "3_Day" DOUBLE PRECISION,
    "4_Day" DOUBLE PRECISION,
    "5_Day" DOUBLE PRECISION,
    "6_Day" DOUBLE PRECISION,
    "7_Day" DOUBLE PRECISION,
    "14_Day" DOUBLE PRECISION,
    "28_Day" DOUBLE PRECISION
);


DROP TABLE IF EXISTS "Rental_Plans";

CREATE TABLE "Rental_Plans" (
    "ID_Number" INTEGER,
    "Plan_Name" TEXT,
    "Max_Rents" INTEGER,
    "Plan_Price" DOUBLE PRECISION,
    "Follow_Up" INTEGER,
    "Rent_Cats" TEXT,
    "Plan_Disc" INTEGER
);


DROP TABLE IF EXISTS "Reservations";

CREATE TABLE "Reservations" (
    "ref" TEXT,
    "Title" TEXT,
    "Member_Number" TEXT,
    "Date_Required" TIMESTAMP,
    "Return_Date" TIMESTAMP,
    "Tagged" TEXT
);


DROP TABLE IF EXISTS "Restriction_Categories";

CREATE TABLE "Restriction_Categories" (
    "Restriction_Category" TEXT,
    "Check_Age" TEXT,
    "Active" TEXT
);


DROP TABLE IF EXISTS "Returned_Loans";

CREATE TABLE "Returned_Loans" (
    "Date_Created" TIMESTAMP,
    "Time_Created" TIMESTAMP,
    "Date_Returned" TIMESTAMP,
    "Time_Returned" TIMESTAMP,
    "Due_Date" TIMESTAMP,
    "Tran_Ref" DOUBLE PRECISION,
    "Ref" TEXT,
    "Title" TEXT,
    "Return_Status" TEXT,
    "Member_Number" TEXT,
    "Cost" DOUBLE PRECISION,
    "Tax" DOUBLE PRECISION,
    "Tax2" DOUBLE PRECISION,
    "Added_By" TEXT,
    "Fr_Rent_Pts" TEXT,
    "Note_X" TEXT,
    "Returned_By" TEXT,
    "Session_id" DOUBLE PRECISION,
    "Rented_By" TEXT,
    "R_Plan" TEXT,
    "Promo_Code" TEXT,
    "T_Ind" TEXT
);


DROP TABLE IF EXISTS "Sales";

CREATE TABLE "Sales" (
    "Date_Time" TIMESTAMP,
    "Time_Created" TIMESTAMP,
    "Tran_Ref" DOUBLE PRECISION,
    "Stock_Code" TEXT,
    "Product_Name" TEXT,
    "Tax" DOUBLE PRECISION,
    "Tax2" DOUBLE PRECISION,
    "Total_Revenue" DOUBLE PRECISION,
    "Quantity" DOUBLE PRECISION,
    "Customer" TEXT,
    "Added_By" TEXT,
    "Fr_Rent_Pts" TEXT,
    "Note_X" TEXT,
    "Sales_Ref" TEXT,
    "Session_id" DOUBLE PRECISION,
    "Promo_Code" TEXT
);


DROP TABLE IF EXISTS "Stock";

CREATE TABLE "Stock" (
    "Stock_Code" TEXT,
    "Product_Name" TEXT,
    "Selling_Price" DOUBLE PRECISION,
    "Purchase_Price" DOUBLE PRECISION,
    "Stock_Level" DOUBLE PRECISION,
    "Tax_Applied" TEXT,
    "Date_Added" TIMESTAMP,
    "Added_By" TEXT,
    "Fr_Rent_Pts" TEXT,
    "Pts_To_Rent" TEXT,
    "Stock_Cat" TEXT,
    "Reorder_Level" DOUBLE PRECISION,
    "Supplier" TEXT,
    "Supp_Phone" TEXT,
    "Order2_Level" DOUBLE PRECISION,
    "OUnit_Cost" DOUBLE PRECISION,
    "Items_Unit" DOUBLE PRECISION,
    "Supp_Ref" TEXT,
    "Addit_Info" TEXT,
    "I_Image" TEXT
);


DROP TABLE IF EXISTS "Terminals";

CREATE TABLE "Terminals" (
    "Date_Log" TIMESTAMP,
    "Time_Log" TIMESTAMP,
    "Termin" DOUBLE PRECISION,
    "C_Name" TEXT,
    "R_Code" TEXT,
    "Us_Code" TEXT
);


DROP TABLE IF EXISTS "Tran_Numbers";

CREATE TABLE "Tran_Numbers" (
    "Date_Stamp" TIMESTAMP,
    "Tran_Ref" DOUBLE PRECISION,
    "Un_ID" TEXT,
    "T_ID" TEXT
);


DROP TABLE IF EXISTS "Transfer_Rules";

CREATE TABLE "Transfer_Rules" (
    "From_Cat" TEXT,
    "To_Cat" TEXT,
    "After_Days" INTEGER
);


DROP TABLE IF EXISTS "Users";

CREATE TABLE "Users" (
    "User" TEXT,
    "Password" TEXT,
    "Rent" TEXT,
    "Reports" TEXT,
    "AddVid" TEXT,
    "AddCust" TEXT,
    "AddCat" TEXT,
    "AddUser" TEXT,
    "Extra1" TEXT,
    "Extra2" TEXT,
    "Points" TEXT,
    "Account" TEXT,
    "CD_Sess" TEXT
);


DROP TABLE IF EXISTS "Videos";

CREATE TABLE "Videos" (
    "Ref" TEXT,
    "Title_Ref" DOUBLE PRECISION,
    "Title" TEXT,
    "Genre" TEXT,
    "Date_Added" TIMESTAMP,
    "Release_Date" TIMESTAMP,
    "Cost_Price" DOUBLE PRECISION,
    "Rental_Category" TEXT,
    "Rental_Time" DOUBLE PRECISION,
    "Rental_Price" DOUBLE PRECISION,
    "Category" TEXT,
    "Location" TEXT,
    "Star1" TEXT,
    "Star2" TEXT,
    "Star3" TEXT,
    "Star4" TEXT,
    "Star5" TEXT,
    "Star6" TEXT,
    "Spare1" TEXT,
    "Spare2" TEXT,
    "Status" TEXT,
    "Tax_Applied" TEXT,
    "Added_By" TEXT,
    "Custom1" TEXT,
    "Custom2" TEXT,
    "Custom3" TEXT,
    "Custom4" TEXT,
    "Synopsis" TEXT,
    "Director" TEXT,
    "Trailer" TEXT,
    "Cover" TEXT,
    "RunTime" TEXT,
    "Keywords" TEXT,
    "Rel_Yr" TEXT
);


DROP TABLE IF EXISTS "Void_Trans";

CREATE TABLE "Void_Trans" (
    "Date_Created" TIMESTAMP,
    "Time_Created" TIMESTAMP,
    "Date_Voided" TIMESTAMP,
    "Time_Voided" TIMESTAMP,
    "Tran_Ref" DOUBLE PRECISION,
    "Ref" TEXT,
    "Title" TEXT,
    "Void_Status" TEXT,
    "Member_Number" TEXT,
    "Cost" DOUBLE PRECISION,
    "Tax" DOUBLE PRECISION,
    "Tax2" DOUBLE PRECISION,
    "Added_By" TEXT,
    "Note_X" TEXT,
    "Voided_By" TEXT,
    "Type" TEXT
);


DROP TABLE IF EXISTS "Wishlists";

CREATE TABLE "Wishlists" (
    "Date_Time" TEXT,
    "Member_Number" TEXT,
    "Title" TEXT,
    "Spare1" TEXT
);

