server {
    listen 8080;
    
    location /up {
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }
    
    location / {
        proxy_pass http://ei-point-of-sale-garage:3900;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
