common: &default_settings
  license_key: <%= ENV.fetch('NEW_RELIC_LICENSE_KEY') { nil } %>
  app_name: 'EI POS'
production:
  <<: *default_settings
  log_level: info
development:
  <<: *default_settings
  log_level: debug