# frozen_string_literal: true

class ReportsController < ApplicationController
  include Filterable

  load_and_authorize_resource except: %i[index new create]
  before_action :set_report, only: %i[show export_pdf export_excel destroy]

  def index
    authorize! :read, Report
    @templates = ReportTemplate.all

    @filter_config = FilterConfig.new(:reports, reports_path,
                                      search_placeholder: "Search reports...") do |f|
      f.select :status, label: "Status",
               options: [ %w[Completed completed], %w[Processing processing], %w[Pending pending], %w[Failed failed] ]
      f.select :report_type, label: "Type",
               options: ReportTemplate.all.map { |t| [ t.title, t.key ] }
      f.date_range :created_at, label: "Created"

      f.column :title,        label: "Title",     default: true, sortable: true
      f.column :report_type,  label: "Type",      default: true, sortable: true
      f.column :status,       label: "Status",    default: true, sortable: true
      f.column :generated_by, label: "Generated by", default: true
      f.column :created_at,   label: "Created",   default: true, sortable: true
    end
    @saved_queries = current_user.saved_queries.for_resource("reports")

    @pagy, @reports = filter_and_paginate(
      Report.includes(:generated_by),
      config: @filter_config
    )
  end

  def new
    authorize! :create, Report
    @template = ReportTemplate.find(params[:template])
    redirect_to reports_path, alert: "Unknown report template." unless @template
  end

  def create
    authorize! :create, Report
    template = ReportTemplate.find(report_params[:report_type])

    unless template
      redirect_to reports_path, alert: "Unknown report template."
      return
    end

    @report = Report.new(
      report_type: template.key,
      title: "#{template.title} — #{Time.current.strftime('%b %d, %Y %l:%M %p')}",
      parameters: report_params[:parameters]&.to_unsafe_h || {},
      generated_by: current_user
    )

    if @report.save
      GenerateReportJob.perform_later(@report.id)
      redirect_to report_path(@report), notice: "Report queued for generation."
    else
      @template = template
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @template = @report.template
  end

  def export_pdf
    unless @report.completed?
      redirect_to report_path(@report), alert: "Report is not ready for export."
      return
    end

    pdf_data = ReportPdfExporter.generate(@report)

    send_data pdf_data,
      filename: pdf_filename,
      type: "application/pdf",
      disposition: "attachment"
  end

  def export_excel
    unless @report.completed?
      redirect_to report_path(@report), alert: "Report is not ready for export."
      return
    end

    xlsx_data = ReportExcelExporter.generate(@report)

    send_data xlsx_data,
      filename: excel_filename,
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      disposition: "attachment"
  end

  def destroy
    @report.destroy
    redirect_to reports_path, notice: "Report deleted."
  end

  private

    def set_report
      @report = Report.find(params[:id])
    end

    def report_params
      params.require(:report).permit(:report_type, parameters: {})
    end

    def pdf_filename
      "#{@report.report_type}_#{@report.id}_#{@report.created_at.strftime('%Y%m%d')}.pdf"
    end

    def excel_filename
      "#{@report.report_type}_#{@report.id}_#{@report.created_at.strftime('%Y%m%d')}.xlsx"
    end
end
